name: my
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.8.2+18

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.1
  package_info: ^0.4.1
  shared_preferences: any
  #date purpose
  intl: ^0.17.0
  #pull to refresh
  pull_to_refresh: ^1.5.8
  #open WhatsApp
  #  flutter_launch: ^0.2.0
  flutter_open_whatsapp: ^0.1.2
  #url
  url_launcher: ^6.0.6
  #radio button
  grouped_buttons: ^1.0.4
  #geocoder
  geocoder: ^0.2.1
  map_launcher: ^0.6.0
  #font
  google_fonts: ^2.0.0
  #toast
  toast: ^0.1.5
  #selection with search
  dropdown_search: ^0.4.3
  #date picker
  flutter_datetime_picker: ^1.5.1
  #firebase_messaging
  firebase_core: ^1.2.1
  firebase_messaging: ^10.0.1
  #notification
  flutter_local_notifications: ^5.0.0+1
  flutter_app_badger: ^1.2.0
  rxdart: ^0.27.1
  #audio
  assets_audio_player: ^3.0.3+3
  #rich text editor
  flutter_quill: ^1.3.3
  delta_markdown: ^0.2.0
  markdown: ^4.0.0
  html2md: ^1.2.4
  #share
  share: ^2.0.1
  #connection
  connectivity: ^3.0.3
  #image picker
  image_picker: ^0.7.4
  #multiple image picker
  multi_image_picker: ^4.7.14
  #image compressor
  flutter_image_compress: ^1.0.0
  #device language
  devicelocale: ^0.3.2
  provider: ^5.0.0
  dotted_line: ^2.0.2
  #csv
  csv: ^4.1.0
  #permission
  permission_handler: ^7.0.0
  path_provider: ^2.0.1
  open_file: ^3.0.3
  #loading
  flutter_spinkit: ^4.1.2+1
  image_cropper: ^1.3.1
  #qr code
  qr_flutter:
    git:
      url: git://github.com/lukef/qr.flutter.git
  #share image
  wc_flutter_share: ^0.4.0
  #color picker
  flutter_colorpicker: ^0.4.0
  #reorderable list view
  refreshable_reorderable_list: ^0.0.1
  countup: ^0.1.3
  cupertino_icons: ^1.0.2
  #printer
  #esc_pos_bluetooth: ^0.2.8
  esc_pos_bluetooth:
    git:
      url: https://github.com/ChannelSoftPlt/esc_pos_bluetooth.git
  flutter_blue: ^0.7.1+1
  esc_pos_printer: ^3.2.9

dependency_overrides:
  rxdart: ^0.27.1
  http: ^0.13.1
  html: ^0.15.0
  args: ^2.1.1
  crypto: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  #app icon
  flutter_launcher_icons: ^0.7.2
flutter_icons:
  image_path: "drawable/new_logo.jpg"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - drawable/
    - audio/
    - language/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages